# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.19' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

steps: 
- task: GoTool@0
  inputs:
    version: '1.19.3'

- task: Bash@3
  inputs:
    targetType: 'inline'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    script: |
      echo "Haciendo go mod download..."
      go mod download
      echo "Haciendo go mod tidy..."
      go mod tidy
      echo "Haciendo go test ./..."
      go test ./...