pool:
  vmImage: ubuntu-latest

steps:
- task: GoTool@0
  inputs:
    version: '1.19.3'

- task: Go@0
  inputs:
    command: 'get'
    arguments: '-t cotan/types/models'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: Go@0
  inputs:
    command: 'test'
    arguments: '-v ./...'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
