version: '3'

tasks:
  check:
    cmds:
      - gofmt -w ./types/models

  test:
    cmds:
      - go test -v ./...

  test-inside-docker:
    cmds:
      - cp -R . ../ejecucion_tests
      - cd ../ejecucion_tests && export ROOT_PATH=`pwd` && go mod tidy && go test -v ./...

  docker:
    cmds:
      - docker run -u 1001 -t -v `pwd`:/app/test iscoct/cotan

  coverage:
    cmds:
      - go test -v ./... -cover
