name: CI/CD del proyecto

on:
  push:
    branches:
      - main
    path-ignores:
      - 'docs/**'
    paths:
      - 'go.mod'
      - 'go.sum'
      - 'Dockerfile'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: iscoct/cotan:latest
