name: Execute the project's unit tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.18', '1.19']

    name: 'Go ${{matrix.go-version}} test'
    env:
      ROOT_PATH: '${{GITHUB_WORKSPACE}}'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.go-version}}

      - name: Install dependencies for specific go version
        run: |
          sed -i 's/1.19/${{matrix.go-version}}/g' go.mod
          go mod download
          go mod tidy
      - name: Execute tests
        run: 'go test -v ./...'
